# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dWbkE1ucKOUJl3uwzb_-bBs5lcwgz_L2
"""
import numpy as np
import weakref

class Variable():
    def __init__(self, data):
        if data is not None:
            if not isinstance(data, np.ndarray):
                raise TypeError('{}은(는) 지원하지 않습니다.'.format(type(data)))
        self.data = data
        self.grad = None # 미분값 저장
        self.creator = None # 인스턴스 변수 추가
        self.generation = 0 # 세대 수를 기록하는 변수

    def set_creator(self, func): # 메서드 추가
        self.creator = func
        self.generation = func.generation + 1 # 세대를 기록 (부모 세대 + 1)

    def cleargrad(self):
        self.grad = None # 여러 가지 미분을 계산할 때 똑같은 변수를 재사용 가능

    def backward(self):
        if self.grad is None:
            self.grad = np.ones_like(self.data) # self.data와 형상과
            # 데이터 터입이 같은 ndarray 인스턴스 생성

        funcs = []
        seen_set = set() # 함수의 backward 메서드가 여러 번 불리는 것 방지

        def add_func(f): # 함수 리스트 세대 순으로 정렬
            if f not in seen_set:
                funcs.append(f)
                seen_set.add(f)
                funcs.sort(key=lambda x: x.generation)

        add_func(self.creator)
        
        while funcs:
            f = funcs.pop() # 1. 함수를 가져온다.
            gys = [output().grad for output in f.outputs] # 약한 참조를 적용하고 출력 변수(미분값)을 리스트에 담는다.
            gxs = f.backward(*gys) # 역전파 호출 : 리스트 언팩
            if not isinstance(gxs, tuple): # 튜플이 아닌 경우 튜플로 변경
                gxs = (gxs, )
            for x, gx in zip(f.inputs, gxs): # 모든 Variable 인스턴스 각각에 알맞은 미분값을 설정
                if x.grad is None:
                    x.grad = gx
                else:
                    x.grad = x.grad + gx # 미분값을 더해준다.

                if x.creator is not None:
                    add_func(x.creator)

# 문제를 해결할 편의 함수
def as_array(x):
    if np.isscalar(x):
        return np.array(x)
    return x

class Function:
    def __call__(self, *inputs): # 임의 개수의 인수(가변 길이 인수)를 건네 함수를 호출할 수 있다.
        xs = [x.data for x in inputs] # input을 리스트로
        ys = self.forward(*xs) # 언팩
        if not isinstance(ys, tuple): # 튜플이 아닌 경우 튜플로 변경
            ys = (ys,)
        outputs = [Variable(as_array(y)) for y in ys] # output을 리스트로

        # 입력 변수와 같은 값으로 generation 설정
        self.generation = max([x.generation for x in inputs])

        for output in outputs:
            output.set_creator(self)
        self.inputs = inputs
        self.outputs = [weakref.ref(output) for output in outputs] # 약한 참조

        # 리스트의 원소가 하나라면 첫 번째 원소를 반환한다.
        return outputs if len(outputs) > 1 else outputs[0]

    def forward(self, x):
        raise NotImplementedError() 

    def backward(self, gy):
        raise NotImplementedError()

class Square(Function):
    def forward(self, x):
        y = x ** 2
        return y

    def backward(self, gy):
        x = self.inputs[0].data # 복수형 inputs로 변경
        gx = 2 * x * gy
        return gx

def square(x):
    f = Square()
    return f(x)

for i in range(10):
    x = Variable(np.random.randn(10000))  # big data
    y = square(square(square(x)))